steps:
# Build the container image and push it with Kaniko
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    [
      "--dockerfile=dockerfile",
      "--cache=true",
      "--cache-ttl=6h",
      "--destination=us-central1-docker.pkg.dev/adroit-nimbus-370411/kpt-tech/image:${SHORT_SHA}"
    ]


# Create release in Google Cloud Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "tech-kpt",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "kpt-tech=us-central1-docker.pkg.dev/adroit-nimbus-370411/kpt-tech/image:${SHORT_SHA}"
    ]
options:
 logging: CLOUD_LOGGING_ONLY
