apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy-1
spec:
  selector:
    matchLabels:
      app: python-deploy-1
  template:
    metadata:
      labels:
        app: python-deploy-1
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: default
      containers:
        - name: python-deploy-1
          image: python-deployment
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
