apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-session
spec:
  selector:
    matchLabels:
      app: kpt-tech
  template:
    metadata:
      labels:
        app: kpt-tech
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: default
      containers:
        - name: kpt-tech
          image: kpt-tech
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
